/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

// import static org.junit.Assert.assertFalse;
// import static org.junit.Assert.assertTrue;
import static org.junit.Assert.assertEquals;

import org.junit.Test;

public class AppTest {

  @Test
  public void testExample() {
    assertEquals(2, 1 + 1);
  }

  // TODO in CHECKER INPUT THE UI SHOULD HAPPEN IN UI FOLDER NOT IN UTILS
  // @Test
  // public void validatesLoginCredentialsFirst() {
  //   // Logging
  //   assertTrue(AppChecker.isValidLoginUsername("payroll_staff"));
  //   assertFalse(AppChecker.isValidLoginUsername(""));

  //   assertTrue(AppChecker.isValidLoginPassword("12345"));
  //   assertFalse(AppChecker.isValidLoginPassword(""));

  //   assertTrue(AppChecker.isValidLoginCredentials("payroll_staff", "12345"));
  //   assertFalse(AppChecker.isValidLoginCredentials("", "12345"));
  //   assertFalse(AppChecker.isValidLoginCredentials("payroll_staff", ""));
  //   assertFalse(AppChecker.isValidLoginCredentials(null, "", "12345"));
  // }

  // @Test
  // public void authenticatesLoginAsEmployeeOrPayrollStaff() {
  //   // Logging as employee or payroll_staff or as specific employee ID
  //   assertFalse(AppChecker.authenticateLogin(null, "baduser", "12345"));
  //   assertTrue(AppChecker.authenticateLogin(null, "payroll_staff", "12345"));
  //   assertTrue(AppChecker.authenticateLogin(null, "employee", "12345"));
  //   assertTrue(AppChecker.authenticateLogin(null, "10001", "12345"));
  // }

  // @Test
  // public void validatesBirthdatesAndNumericFields() {
  //   assertTrue(PayrollServiceChecker.isValidBirthDate("12/31/1999"));
  //   assertFalse(PayrollServiceChecker.isValidBirthDate("31/12/1999"));
  //   assertFalse(PayrollServiceChecker.isValidBirthDate("MM/DD/YYYY"));

  //   assertTrue(PayrollServiceChecker.isValidPhoneNumber("09171234567"));
  //   assertFalse(PayrollServiceChecker.isValidPhoneNumber("0917-123-4567"));

  //   assertTrue(PayrollServiceChecker.isValidNumericValue("15000.50"));
  //   assertFalse(PayrollServiceChecker.isValidNumericValue("abc"));
  // }

  // @Test
  // public void validatesGovernmentIds() {
  //   assertTrue(PayrollServiceChecker.isValidSss("52-2061274-9"));
  //   assertFalse(PayrollServiceChecker.isValidSss("52-20612749"));

  //   assertTrue(PayrollServiceChecker.isValidPhilHealth("331735646338"));
  //   assertFalse(PayrollServiceChecker.isValidPhilHealth("33173564633A"));

  //   assertTrue(PayrollServiceChecker.isValidTin("683-102-776-000"));
  //   assertFalse(PayrollServiceChecker.isValidTin("683102776000"));

  //   assertTrue(PayrollServiceChecker.isValidPagIbig("663904995411"));
  //   assertFalse(PayrollServiceChecker.isValidPagIbig("663-904-995-411"));
  // }

  // @Test
  // public void validatesPayslipRequestThroughChecker() {
  //   assertFalse(PayrollServiceChecker.validatePayslipRequest(null, "", false, "", null));
  //   assertFalse(PayrollServiceChecker.validatePayslipRequest(null, "10002", true, "10001",
  // null));
  //   assertTrue(
  //       PayrollServiceChecker.validatePayslipRequest(
  //           null, "10001", true, "10001", new String[] {"10001"}));
  // }

  // @Test
  // public void validatesEmployeeFormThroughChecker() {
  //   assertFalse(PayrollServiceChecker.validateRequiredNames(null, "", ""));
  //   assertTrue(PayrollServiceChecker.validateRequiredNames(null, "Doe", "John"));

  //   assertTrue(
  //       PayrollServiceChecker.validateEmployeeInput(
  //           null,
  //           "12/31/1999",
  //           "09171234567",
  //           "52-2061274-9",
  //           "331735646338",
  //           "683-102-776-000",
  //           "663904995411",
  //           "15000",
  //           "1000",
  //           "500",
  //           "1000",
  //           "30000",
  //           "250"));

  //   assertFalse(
  //       PayrollServiceChecker.validateEmployeeInput(
  //           null,
  //           "31/12/1999",
  //           "0917-123-4567",
  //           "52-20612749",
  //           "33173564633A",
  //           "683102776000",
  //           "663-904-995-411",
  //           "-100",
  //           "-10",
  //           "-5",
  //           "-2",
  //           "-1",
  //           "-3"));
  // }
}
